### ISSUE TITLE
Citrix Gateway (formerly known as Netscaler Gateway) deployment?

### ISSUE THREAD

**Issue by riahc3** [ryancbutler/Citrix-VAD-LAB#1]
First, thanks for making this. Its really helps.

I just wanted to know if anything with Ansible and Citrix Gateway (formerly known as Netscaler Gateway) is in your plans.

Thank you!

**Comment by ryancbutler** [comment]
Glad it helps and thanks for the comment.  I have been thinking about how to approach it.  I already have the spin-up of the ADC then Storefront and Director load balancing working in my lab.  The problem is the licensing when it comes to Gateway since it requires a license in order to function.  Which is tied to a MAC address...  So either the clone of the VM needs to set the same MAC or need to use an existing ADC.

**Comment by riahc3** [comment]
> Glad it helps and thanks for the comment. I have been thinking about how to approach it. I already have the spin-up of the ADC then Storefront and Director load balancing working in my lab. The problem is the licensing when it comes to Gateway since it requires a license in order to function. Which is tied to a MAC address... So either the clone of the VM needs to set the same MAC or need to use an existing ADC.

Im not sure if its possible in ansible but....wouldnt sending a raw ssh command to the netscaler and lmutil lmhostid be enough to retrieve the MAC?

Or do you mean get the MAC, connect to Citrix licencing page,, generate a lic file, install it, etc?

**Comment by ryancbutler** [comment]
Basically you would be stuck generating the license ahead of time with the MAC address of your template.  And then for any clones of the ADC you would have to make sure the MAC is set to the same.  

I don't believe Citrix has any sort of API on the licensing page to allow automation.

The other option is utilizing pool licensing but that is another process to manage.

**Comment by riahc3** [comment]
> Basically you would be stuck generating the license ahead of time with the MAC address of your template. And then for any clones of the ADC you would have to make sure the MAC is set to the same.
> 
> I don't believe Citrix has any sort of API on the licensing page to allow automation.
> 
> The other option is utilizing pool licensing but that is another process to manage.

Ah, OK, I think you are thinking of Terraform while Im just thinking about the Ansible part. Sorry about that.

I apoligize as I dont know how Terraform works exactly so Im not exactly sure of the issue although I imagine its similar to cloning VMs and having different MAC addresses.

Thanks for all your work! Ill be testing each part so expect more questions/issues from me ;)
