### ISSUE TITLE
Storefront-Init Slurp Passcode File

### ISSUE THREAD

**Issue by SpodoY** [ryancbutler/Citrix-VAD-LAB#11]
Hi!

I deployed my VMs manually and everything worked out fine for now.

When I get to the storefront-init Task, everything runs smoothly until the last task (slurp passcode). Here it tells me the file (C:\\Logs\\passcode.txt) was not found. 

I am quite confused as to where, and how the file is genereted inside your script. I know it is needed to join the second server but since I have no file I can't continue. 

My Citrix CVAD Version is 2203 and I am working on Windows Server 2022 Machienes. Can you maybe tell me where I'm mistaken ?

**Comment by ryancbutler** [comment]
This file gets created here https://github.com/ryancbutler/Citrix-VAD-LAB/blob/309228ae5a24d37dcd8976b97567f13ffc980bbe/ansible/roles/storefront-init/files/createsfsite.ps1
