### ISSUE TITLE
Error: error fetching resource pool: resource pool

### ISSUE THREAD

**Issue by extromen13** [ryancbutler/Citrix-VAD-LAB#9]
Hi,
currently there is a problem with fetching resource pool
every time I am getting this error
Error: error fetching resource pool: resource pool 'WAG/INFRA' not found

  on main.tf line 19, in data "vsphere_resource_pool" "pool":
  19: data vsphere_resource_pool "pool" {

Can you please advise what is wrong?
Thanks a lot
TN

**Comment by ryancbutler** [comment]
Sounds like the resource pool WAG\INFRA can't be found. Make sure its the correct case. https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/data-sources/resource_pool

**Comment by extromen13** [comment]
HI @ryancbutler 
the problem is with any name I am giving as resource pool, I also tried the root resource pool

> "Specifying the root resource pool for a standalone host
> NOTE:
> Fetching the root resource pool for a cluster can now be done directly via the vsphere_compute_cluster data source.
> 
> All compute resources in vSphere (clusters, standalone hosts, and standalone ESXi) have a resource pool, even if one has not been explicitly created. This resource pool is referred to as the root resource pool and can be looked up by specifying the path as per the example below:
> 
> data "vsphere_resource_pool" "pool" {
>   name          = "esxi1/Resources"
>   datacenter_id = "${data.vsphere_datacenter.dc.id}"
> }

is there a way how to list resource pool name via terraform? I have no other idea how to find out what is wrong, I also found some threads that are pointing to the same issue with resource pool

https://github.com/hashicorp/terraform-provider-vsphere/issues/962
Thanks a lot
